version: '3'

services:
  app:
    container_name: redix_sentinel
    image: bitwalker/alpine-elixir:1.5.1
    volumes:
      - .:/opt/app
    links:
      - redis_1
      - redis_2
      - redis_3
      - sentinel_1
      - sentinel_2
      - sentinel_3
  redis_1:
    container_name: redis_1
    build:
      context: ./docker/
    command: ["redis-server", "/usr/local/etc/redis/redis_1.conf"]
    ports:
      - "1379:1379"
  redis_2:
    container_name: redis_2
    build:
      context: ./docker/
    command: ["redis-server", "/usr/local/etc/redis/redis_2.conf"]
    ports:
      - "2379:2379"
  redis_3:
    container_name: redis_3
    build:
      context: ./docker/
    command: ["redis-server", "/usr/local/etc/redis/redis_3.conf"]
    ports:
      - "3379:3379"
  sentinel_1:
    container_name: sentinel_1
    build:
      context: ./docker/
    command: ["redis-server", "/usr/local/etc/redis/sentinel_1.conf", "--sentinel"]
    ports:
      - "10000:10000"
  sentinel_2:
    container_name: sentinel_2
    build:
      context: ./docker/
    command: ["redis-server", "/usr/local/etc/redis/sentinel_2.conf", "--sentinel"]
    ports:
      - "20000:20000"
  sentinel_3:
    container_name: sentinel_3
    build:
      context: ./docker/
    command: ["redis-server", "/usr/local/etc/redis/sentinel_3.conf", "--sentinel"]
    ports:
      - "30000:30000"
